import { env } from "@/src/env";

const defaultIcons = {
	backpack: "/icons/backpack.png",
	camera: "/icons/camera.png",
	keychain: "/icons/keychain.png",
	popcornBucket: "/icons/popcorn-bucket.png",
	server: "/icons/server.png",
	beamer: "/icons/beamer.png",
	headphones: "/icons/headphones.png",
	lock: "/icons/lock.png",
	recordPlayer: "/icons/record-player.png",
	tv: "/icons/tv.png",
	book: "/icons/book.png",
	bookshelf: "/icons/bookshelf.png",
	cog: "/icons/cog.png",
	datacenter: "/icons/datacenter.png",
	documents: "/icons/documents.png",
	house: "/icons/house.png",
	pieChart: "/icons/pie-chart.png",
	powerPlug: "/icons/power-plug.png",
	questionMark: "/icons/question-mark.png",
	speechBubble: "/icons/speech-bubble.png",
	amber: "/icons/amber.png",
	amethyst: "/icons/amethyst.png",
	neutral: "/icons/neutral.png",
	sunshine: "/icons/sunshine.png",
	lime: "/icons/lime.png",
	compass: "/icons/compass.png",
	blueprint: "/icons/blueprint.png",
	ocean: "/icons/ocean.png",
};

const extraIcons = {
	playOnFilmstrip: "/icons/extra/play-on-filmstrip.png",
	beaverCloudFur: "/icons/extra/beaver-cloud-fur.png",
	n8n: "/icons/extra/n8n.png",
	curvedPhoneReceiverStars: "/icons/extra/curved-phone-receiver-stars.png",
	threeArrowsMerge: "/icons/extra/three-arrows-merge.png",
	magicWandStackedPages: "/icons/extra/magic-wand-stacked-pages.png",
	orangeCoinLightning: "/icons/extra/orange-coin-lightning.png",
	qbittorrent: "/icons/extra/qbittorrent.png",
	dashy: "/icons/extra/dashy.png",
	stackedFoldersOpenTab: "/icons/extra/stacked-folders-open-tab.png",
	gitea: "/icons/extra/gitea.png",
	stackedLetterTilesQuestion: "/icons/extra/stacked-letter-tiles-question.png",
	redmine: "/icons/extra/redmine.png",
	umami: "/icons/extra/umami.png",
	freshrss: "/icons/extra/freshrss.png",
	mountainSignalWaves: "/icons/extra/mountain-signal-waves.png",
	syncLoopArrows: "/icons/extra/sync-loop-arrows.png",
	funkwhale: "/icons/extra/funkwhale.png",
	glances: "/icons/extra/glances.png",
	papermerge: "/icons/extra/papermerge.png",
	squidTentacleWebpage: "/icons/extra/squid-tentacle-webpage.png",
	stackedBoxes: "/icons/extra/stacked-boxes.png",
	newsScrollInkPen: "/icons/extra/news-scroll-ink-pen.png",
	syncthing: "/icons/extra/syncthing.png",
	paperPlaneFileBox: "/icons/extra/paper-plane-file-box.png",
	nozzleFlowingLiquid: "/icons/extra/nozzle-flowing-liquid.png",
	gridConnectedPuzzle: "/icons/extra/grid-connected-puzzle.png",
	transmission: "/icons/extra/transmission.png",
	unifiController: "/icons/extra/unifi-controller.png",
	featherOnPaper: "/icons/extra/feather-on-paper.png",
	stackedEnvelopesTiedString: "/icons/extra/stacked-envelopes-tied-string.png",
	redNodeFlowingWires: "/icons/extra/red-node-flowing-wires.png",
	caddy: "/icons/extra/caddy.png",
	sabnzbd: "/icons/extra/sabnzbd.png",
	ombi: "/icons/extra/ombi.png",
	calibreWeb: "/icons/extra/calibre-web.png",
	prometheus: "/icons/extra/prometheus.png",
	piHole: "/icons/extra/pi-hole.png",
	traefik: "/icons/extra/traefik.png",
	scissorsFilmStrips: "/icons/extra/scissors-film-strips.png",
	jellyfin: "/icons/extra/jellyfin.png",
	libretranslate: "/icons/extra/libretranslate.png",
	owncast: "/icons/extra/owncast.png",
	silverRibbonWeavingBlocks: "/icons/extra/silver-ribbon-weaving-blocks.png",
	puzzlePiecesLightningBolt: "/icons/extra/puzzle-pieces-lightning-bolt.png",
	bookDownloadGlow: "/icons/extra/book-download-glow.png",
	sonarr: "/icons/extra/sonarr.png",
	circuitBoard: "/icons/extra/circuit-board.png",
	kanboard: "/icons/extra/kanboard.png",
	eyeShield: "/icons/extra/eye-shield.png",
	nextcloud: "/icons/extra/nextcloud.png",
	controlPanelLevers: "/icons/extra/control-panel-levers.png",
	keycloak: "/icons/extra/keycloak.png",
	paperToPdf: "/icons/extra/paper-to-pdf.png",
	serverMusicNotes: "/icons/extra/server-music-notes.png",
	orangeFoxKeyRing: "/icons/extra/orange-fox-key-ring.png",
	puzzlePieceXmlTags: "/icons/extra/puzzle-piece-xml-tags.png",
	lockedBundleChatBubble: "/icons/extra/locked-bundle-chat-bubble.png",
	lidarr: "/icons/extra/lidarr.png",
	paperAirplaneDottedPath: "/icons/extra/paper-airplane-dotted-path.png",
	nginxProxyManager: "/icons/extra/nginx-proxy-manager.png",
	magicScroll: "/icons/extra/magic-scroll.png",
	docker: "/icons/extra/docker.png",
	adguardHome: "/icons/extra/adguard-home.png",
	paperlessNgx: "/icons/extra/paperless-ngx.png",
	graphBarsMagnifyingGlass: "/icons/extra/graph-bars-magnifying-glass.png",
	portainer: "/icons/extra/portainer.png",
	rockMetalFistCrushingHill: "/icons/extra/rock-metal-fist-crushing-hill.png",
	wallabag: "/icons/extra/wallabag.png",
	colorfulStickyNotesBoard: "/icons/extra/colorful-sticky-notes-board.png",
	plex: "/icons/extra/plex.png",
	wikiJs: "/icons/extra/wiki-js.png",
	scrollingParchmentCheckmarks:
		"/icons/extra/scrolling-parchment-checkmarks.png",
	netdata: "/icons/extra/netdata.png",
	translucentSheetFloatingQuill:
		"/icons/extra/translucent-sheet-floating-quill.png",
	foxCodeBrackets: "/icons/extra/fox-code-brackets.png",
	flamingSpeechBubbles: "/icons/extra/flaming-speech-bubbles.png",
	quillOverDottedCircle: "/icons/extra/quill-over-dotted-circle.png",
	wordpress: "/icons/extra/wordpress.png",
	stackedBoxesWelcomeTag: "/icons/extra/stacked-boxes-welcome-tag.png",
	pawSpeechBubble: "/icons/extra/paw-speech-bubble.png",
	whisperingBubblesFadingTails:
		"/icons/extra/whispering-bubbles-fading-tails.png",
	glowingRedButtonPodium: "/icons/extra/glowing-red-button-podium.png",
	gitlab: "/icons/extra/gitlab.png",
	searxng: "/icons/extra/searxng.png",
	grafana: "/icons/extra/grafana.png",
	koel: "/icons/extra/koel.png",
	audiobookshelf: "/icons/extra/audiobookshelf.png",
	slidingPanelsDots: "/icons/extra/sliding-panels-dots.png",
	mattermost: "/icons/extra/mattermost.png",
	crumpledPaperTrashCan: "/icons/extra/crumpled-paper-trash-can.png",
	colorfulChainLinks: "/icons/extra/colorful-chain-links.png",
	tuningForkSoundWaves: "/icons/extra/tuning-fork-sound-waves.png",
	openBookFloatingCubes: "/icons/extra/open-book-floating-cubes.png",
	scalesOverBook: "/icons/extra/scales-over-book.png",
	peertube: "/icons/extra/peertube.png",
	envelopeRadiatingWaves: "/icons/extra/envelope-radiating-waves.png",
	barChartMagnifying: "/icons/extra/bar-chart-magnifying.png",
	ghost: "/icons/extra/ghost.png",
	boxOutgoingArrow: "/icons/extra/box-outgoing-arrow.png",
	radarr: "/icons/extra/radarr.png",
};

let icons: Record<string, string> = defaultIcons;

if (env.NEXT_PUBLIC_APP_SIZE === "slim") {
	icons = defaultIcons;
} else {
	icons = { ...defaultIcons, ...extraIcons };
}

export { icons };
