export const icons = {
	backpack: "/icons/backpack.png",
	camera: "/icons/camera.png",
	keychain: "/icons/keychain.png",
	popcornBucket: "/icons/popcorn-bucket.png",
	server: "/icons/server.png",
	beamer: "/icons/beamer.png",
	headphones: "/icons/headphones.png",
	lock: "/icons/lock.png",
	recordPlayer: "/icons/record-player.png",
	tv: "/icons/tv.png",
	book: "/icons/book.png",
	bookshelf: "/icons/bookshelf.png",
	cog: "/icons/cog.png",
	datacenter: "/icons/datacenter.png",
	documents: "/icons/documents.png",
	house: "/icons/house.png",
	pieChart: "/icons/pie-chart.png",
	powerPlug: "/icons/power-plug.png",
	questionMark: "/icons/question-mark.png",
	speechBubble: "/icons/speech-bubble.png",
	amber: "/icons/amber.png",
	amethyst: "/icons/amethyst.png",
	neutral: "/icons/neutral.png",
	sunshine: "/icons/sunshine.png",
	lime: "/icons/lime.png",
};
