name: Build and Push Docker image (Release)

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Enable multi-arch builds (e.g. amd64 + arm64)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKER_USERNAME }}/iso:${{ github.sha }}
            ${{ vars.DOCKER_USERNAME }}/iso:${{ github.event.release.tag_name }}
            ${{ vars.DOCKER_USERNAME }}/iso:latest

      - name: Build and push Docker image (slim)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.slim
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKER_USERNAME }}/iso:${{ github.sha }}-slim
            ${{ vars.DOCKER_USERNAME }}/iso:${{ github.event.release.tag_name }}-slim
            ${{ vars.DOCKER_USERNAME }}/iso:latest-slim 